name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  label-detector:
    name: Runner Label
    runs-on: label-detector
    outputs:
      runs-on: ${{ steps.detector.outputs.label }}
    steps:
      - name: Detect Label
        id: detector
        run: |
          # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
          echo "label=$(curl -fsSL https://this-is-nats.appscode.ninja/runs-on/${{ github.repository_owner }}?visibility=${{ github.repository_visibility }})" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: label-detector
    runs-on: "${{ needs.label-detector.outputs.runs-on }}"
    steps:
      - name: Set up Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
        id: go

      - uses: actions/checkout@v4

      - name: Run checks
        run: |
          make ci
